//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeOdevi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Zimmet
    {
        public int ZimmetId { get; set; }
        [Required(ErrorMessage = "Kullanýcý boþ býrakýlamaz")]
        public Nullable<int> KullaniciID { get; set; }
        [Required(ErrorMessage = "Ürün Adý boþ býrakýlamaz")]
        public Nullable<int> UrunID { get; set; }
        public Nullable<bool> ArizaDurmu { get; set; }
        public Nullable<int> HazirPcParcalariID { get; set; }

        public virtual Tbl_HazirPcParcalari Tbl_HazirPcParcalari { get; set; }
        public virtual Tbl_Kullanici Tbl_Kullanici { get; set; }
        public virtual Tbl_Urun Tbl_Urun { get; set; }
    }
}
