//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeOdevi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Urun()
        {
            this.Tbl_HazirPcParcalari = new HashSet<Tbl_HazirPcParcalari>();
            this.Tbl_Stok = new HashSet<Tbl_Stok>();
            this.Tbl_Zimmet = new HashSet<Tbl_Zimmet>();
        }

        public int UrunId { get; set; }
        [Display(Name = "Ürün Adý")]
        [Required(ErrorMessage = "Adý alaný boþ býrakýlamaz")]
        public string Adi { get; set; }
        [Required(ErrorMessage = "Barkot numarasý boþ býrakýlamaz")]
        public Nullable<int> BarkotNo { get; set; }
        [Display(Name = "Kategori Adý")]
        [Required(ErrorMessage = "Kategori adý boþ býrakýlamaz")]
        public Nullable<int> KategoriID { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        [Required(ErrorMessage = "Fiyat boþ býrakýlamaz")]
        [Display(Name = "Toplam Fiyat")]
        [Range(1, 100000000000000, ErrorMessage = "Çok yüksek veya düþük bir fiyat girdiniz.")]
        public Nullable<decimal> ToptanFiyat { get; set; }
        public Nullable<System.DateTime> SatinAlmaTarihi { get; set; }
        public Nullable<bool> ZimmetDurumu { get; set; }
        [Required(ErrorMessage = "Firma Adý boþ býrakýlamaz")]
        [Display(Name = "Firma Adý")]
        public Nullable<int> FirmaID { get; set; }
        public Nullable<bool> HazirPcMi { get; set; }
        public Nullable<bool> ParcaEklendiMi { get; set; }
        [Required(ErrorMessage = "Adet boþ býrakýlamaz")]
        [Display(Name = "Ürün Adeti")]
        public Nullable<int> Adet { get; set; }
    
        public virtual Tbl_Firma Tbl_Firma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_HazirPcParcalari> Tbl_HazirPcParcalari { get; set; }
        public virtual Tbl_Kategori Tbl_Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Stok> Tbl_Stok { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Zimmet> Tbl_Zimmet { get; set; }
    }
}
